function vars = invars ()
    vars = {
        'Kw';
        'KCh';
        'Dsi';
        'ZgD';
        'PDF';
        'ZDF';
        'muPgC';
        'muPCh';
        'muPRN';
        'muASN';
        'muZin';
        'muZCl';
        'muZgE';
        'muDre';
        'muZmQ';
        'PgC';
        'PCh';
        'PRN';
        'ASN';
        'Zin';
        'ZCl';
        'ZgE';
        'Dre';
        'ZmQ';
        'EZ';
        'Chla';
        'P';
        'Z';
        'D';
        'N';
    };
end
