/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ALPHAQNODE_CUH
#define BIM_NPZD_ALPHAQNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\alpha^Q\f$; 
 *
 * \f$0.02\f$
 */
class AlphaQNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  AlphaQNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(AlphaQNode)

inline AlphaQNode::AlphaQNode() {
  setName("alphaQ");
}

#endif

