/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ALPHAANODE_CUH
#define BIM_NPZD_ALPHAANODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\alpha^A\f$; 
 *
 * \f$0.37\f$
 */
class AlphaANode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  AlphaANode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(AlphaANode)

inline AlphaANode::AlphaANode() {
  setName("alphaA");
}

#endif

