/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ALPHALNODE_CUH
#define BIM_NPZD_ALPHALNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\alpha^L\f$; 
 *
 * \f$0.01\f$
 */
class AlphaLNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  AlphaLNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(AlphaLNode)

inline AlphaLNode::AlphaLNode() {
  setName("alphaL");
}

#endif

