/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ALPHACNODE_CUH
#define BIM_NPZD_ALPHACNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\alpha^C\f$; 
 *
 * \f$1.2\f$
 */
class AlphaCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  AlphaCNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(AlphaCNode)

inline AlphaCNode::AlphaCNode() {
  setName("alphaC");
}

#endif

