/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ALPHACNNODE_CUH
#define BIM_NPZD_ALPHACNNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\alpha^{CN}\f$; 
 *
 * \f$0.4\f$
 */
class AlphaCNNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  AlphaCNNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(AlphaCNNode)

inline AlphaCNNode::AlphaCNNode() {
  setName("alphaCN");
}

#endif

