/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ALPHARNODE_CUH
#define BIM_NPZD_ALPHARNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\alpha^R\f$; 
 *
 * \f$\f$
 */
class AlphaRNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  AlphaRNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(AlphaRNode)

inline AlphaRNode::AlphaRNode() {
  setName("alphaR");
}

#endif

