/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_BETAENODE_CUH
#define BIM_NPZD_BETAENODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\beta^E\f$; Exchange rate
 *
 * \f$\f$
 */
class BetaENode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  BetaENode();

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(BetaENode)

inline BetaENode::BetaENode() {
  setName("betaE");
}

#endif

