/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_BETAPNODE_CUH
#define BIM_NPZD_BETAPNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\beta^P\f$; Phytoplankton boundary condition
 *
 * \f$\f$
 */
class BetaPNode : public bi::BayesNode {
public:

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(BetaPNode)

#endif

