/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_BETAZNODE_CUH
#define BIM_NPZD_BETAZNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\beta^Z\f$; Zooplankton boundary condition
 *
 * \f$\f$
 */
class BetaZNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  BetaZNode();

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(BetaZNode)

inline BetaZNode::BetaZNode() {
  setName("betaZ");
}

#endif

