/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_BETADNODE_CUH
#define BIM_NPZD_BETADNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\beta^D\f$; Detritus boundary condition
 *
 * \f$\f$
 */
class BetaDNode : public bi::BayesNode {
public:

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(BetaDNode)

#endif

