/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ENODE_CUH
#define BIM_NPZD_ENODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$E\f$; Surface irradience
 *
 * \f$\f$
 */
class ENode : public bi::BayesNode {
public:

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(ENode)

#endif

