/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_EZNODE_CUH
#define BIM_NPZD_EZNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$E^Z\f$; Light at depth
 *
 * \f$\frac{E(1-\exp(-K^Z))}{K^Z}\f$
 */
class EZNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  EZNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(EZNode)

inline EZNode::EZNode() {
  setName("EZ");
}

#endif

