/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_LNODE_CUH
#define BIM_NPZD_LNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$L\f$; Mixed layer depth
 *
 * \f$\f$
 */
class LNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  LNode();

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(LNode)

inline LNode::LNode() {
  setName("L");
}

#endif

