/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_MUCHNODE_CUH
#define BIM_NPZD_MUCHNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\mu^{Ch}\f$; Maximum growth rate for Chl-a:C
 *
 * \f$0.03\f$
 */
class MuChNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  MuChNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(MuChNode)

inline MuChNode::MuChNode() {
  setName("muCh");
}

#endif

