/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_MUCNNODE_CUH
#define BIM_NPZD_MUCNNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\mu^{CN}\f$; Maximum growth rate for C:N
 *
 * \f$0.4\f$
 */
class MuCNNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  MuCNNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(MuCNNode)

inline MuCNNode::MuCNNode() {
  setName("muCN");
}

#endif

