/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_MUCNODE_CUH
#define BIM_NPZD_MUCNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\mu^C\f$; Maximum growth rate for C
 *
 * \f$1.2\f$
 */
class MuCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  MuCNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(MuCNode)

inline MuCNode::MuCNode() {
  setName("muC");
}

#endif

