/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_NPZD_CUH
#define BIM_NPZD_NPZD_CUH

#include "BetaPNode.cuh"
#include "BetaZNode.cuh"
#include "BetaNNode.cuh"
#include "BetaDNode.cuh"
#include "TNode.cuh"
#include "ENode.cuh"
#include "LNode.cuh"
#include "BetaENode.cuh"
#include "PNode.cuh"
#include "ZNode.cuh"
#include "DNode.cuh"
#include "NNode.cuh"

#include "bi/model/NodeSpec.hpp"
#include "bi/model/BayesNet.hpp"

/**
 * In-net spec.
 */
BEGIN_NODESPEC(NPZDInSpec)

END_NODESPEC()

/**
 * Ex-net spec
 */
BEGIN_NODESPEC(NPZDExSpec)
SINGLE_TYPE(1, PNode)
SINGLE_TYPE(1, ZNode)
SINGLE_TYPE(1, DNode)
SINGLE_TYPE(1, NNode)
END_NODESPEC()

/**
 * R-net spec
 */
BEGIN_NODESPEC(NPZDRSpec)

END_NODESPEC()

/**
 * F-net spec
 */
BEGIN_NODESPEC(NPZDFSpec)
SINGLE_TYPE(1, BetaPNode)
SINGLE_TYPE(1, BetaZNode)
SINGLE_TYPE(1, BetaNNode)
SINGLE_TYPE(1, BetaDNode)
SINGLE_TYPE(1, TNode)
SINGLE_TYPE(1, ENode)
SINGLE_TYPE(1, LNode)
SINGLE_TYPE(1, BetaENode)
END_NODESPEC()

/**
 * 
 */
class NPZDModel : public bi::BayesNet<
    GET_NODESPEC(NPZDInSpec),
    GET_NODESPEC(NPZDExSpec),
    GET_NODESPEC(NPZDRSpec),
    GET_NODESPEC(NPZDFSpec)> {
public:
  /**
   * Constructor.
   */
  NPZDModel();

  /*
   * Nodes.
   */
  BetaPNode betaP;
  BetaZNode betaZ;
  BetaNNode betaN;
  BetaDNode betaD;
  TNode T;
  ENode E;
  LNode L;
  BetaENode betaE;
  PNode P;
  ZNode Z;
  DNode D;
  NNode N;

};

#endif

