/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#include "NPZDModel.cuh"

NPZDModel::NPZDModel() : bi::BayesNet<
    GET_NODESPEC(NPZDInSpec),
    GET_NODESPEC(NPZDExSpec),
    GET_NODESPEC(NPZDRSpec),
    GET_NODESPEC(NPZDFSpec)>() {
  /* nodes */
  addNode(betaP);
  addNode(betaZ);
  addNode(betaN);
  addNode(betaD);
  addNode(T);
  addNode(E);
  addNode(L);
  addNode(betaE);
  addNode(P);
  addNode(Z);
  addNode(D);
  addNode(N);

  /* edges */
  addArc(T, P);
  addArc(E, P);
  addArc(N, P);
  addArc(P, P);
  addArc(Z, P);
  addArc(betaE, P);
  addArc(betaP, P);
  addArc(Z, Z);
  addArc(T, Z);
  addArc(P, Z);
  addArc(betaE, Z);
  addArc(betaZ, Z);
  addArc(Z, D);
  addArc(T, D);
  addArc(P, D);
  addArc(D, D);
  addArc(L, D);
  addArc(betaE, D);
  addArc(betaD, D);
  addArc(T, N);
  addArc(E, N);
  addArc(N, N);
  addArc(P, N);
  addArc(Z, N);
  addArc(betaE, N);
  addArc(betaN, N);
}

