/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_NUANODE_CUH
#define BIM_NPZD_NUANODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\nu^A\f$; Maximum N affinity
 *
 * \f$0.37\f$
 */
class NuANode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  NuANode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(NuANode)

inline NuANode::NuANode() {
  setName("nuA");
}

#endif

