/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_NURNODE_CUH
#define BIM_NPZD_NURNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\nu^R\f$; Remineralisation rate
 *
 * \f$0.1\f$
 */
class NuRNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  NuRNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(NuRNode)

inline NuRNode::NuRNode() {
  setName("nuR");
}

#endif

