/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_PINCNODE_CUH
#define BIM_NPZD_PINCNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\pi^{NC}\f$; Min/Max N:C
 *
 * \f$0.25\f$
 */
class PiNCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  PiNCNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(PiNCNode)

inline PiNCNode::PiNCNode() {
  setName("piNC");
}

#endif

