/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMANCNODE_CUH
#define BIM_NPZD_SIGMANCNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^{NC}\f$; 
 *
 * \f$0\f$
 */
class SigmaNCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaNCNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaNCNode)

inline SigmaNCNode::SigmaNCNode() {
  setName("sigmaNC");
}

#endif

