/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMACNODE_CUH
#define BIM_NPZD_SIGMACNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^C\f$; 
 *
 * \f$0\f$
 */
class SigmaCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaCNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaCNode)

inline SigmaCNode::SigmaCNode() {
  setName("sigmaC");
}

#endif

