/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMAINODE_CUH
#define BIM_NPZD_SIGMAINODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^I\f$; 
 *
 * \f$\f$
 */
class SigmaINode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaINode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaINode)

inline SigmaINode::SigmaINode() {
  setName("sigmaI");
}

#endif

