/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMACLNODE_CUH
#define BIM_NPZD_SIGMACLNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^{Cl}\f$; 
 *
 * \f$\f$
 */
class SigmaClNode : public bi::BayesNode {
public:

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaClNode)

#endif

