/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMAANODE_CUH
#define BIM_NPZD_SIGMAANODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^A\f$; 
 *
 * \f$0\f$
 */
class SigmaANode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaANode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaANode)

inline SigmaANode::SigmaANode() {
  setName("sigmaA");
}

#endif

