/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMACHNODE_CUH
#define BIM_NPZD_SIGMACHNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^{Ch}\f$; 
 *
 * \f$\f$
 */
class SigmaChNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaChNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaChNode)

inline SigmaChNode::SigmaChNode() {
  setName("sigmaCh");
}

#endif

