/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMARNODE_CUH
#define BIM_NPZD_SIGMARNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^R\f$; 
 *
 * \f$0\f$
 */
class SigmaRNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaRNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaRNode)

inline SigmaRNode::SigmaRNode() {
  setName("sigmaR");
}

#endif

