/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMALNODE_CUH
#define BIM_NPZD_SIGMALNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^L\f$; 
 *
 * \f$\f$
 */
class SigmaLNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaLNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaLNode)

inline SigmaLNode::SigmaLNode() {
  setName("sigmaL");
}

#endif

