/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMAENODE_CUH
#define BIM_NPZD_SIGMAENODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^E\f$; 
 *
 * \f$\f$
 */
class SigmaENode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaENode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaENode)

inline SigmaENode::SigmaENode() {
  setName("sigmaE");
}

#endif

