/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_SIGMACNNODE_CUH
#define BIM_NPZD_SIGMACNNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\sigma^{CN}\f$; 
 *
 * \f$0\f$
 */
class SigmaCNNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  SigmaCNNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(SigmaCNNode)

inline SigmaCNNode::SigmaCNNode() {
  setName("sigmaCN");
}

#endif

