/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_TNODE_CUH
#define BIM_NPZD_TNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$T\f$; Water temperature
 *
 * \f$\f$
 */
class TNode : public bi::BayesNode {
public:

};

#include "bi/model/NodeTypeTraits.hpp"

IS_F_NODE(TNode)

#endif

