/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UANODE_CUH
#define BIM_NPZD_UANODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^A\f$; 
 *
 * \f$u^A \sim \mathcal{N}(0,1)\f$
 */
class UANode : public bi::BayesNode {
public:

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UANode)
IS_R_NODE(UANode)

#endif

