/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UCHNODE_CUH
#define BIM_NPZD_UCHNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^{Ch}\f$; 
 *
 * \f$u^{Ch} \sim \mathcal{N}(0,1)\f$
 */
class UChNode : public bi::BayesNode {
public:

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UChNode)
IS_R_NODE(UChNode)

#endif

