/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UCLNODE_CUH
#define BIM_NPZD_UCLNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^{Cl}\f$; 
 *
 * \f$u^{Cl} \sim \mathcal{N}(0,1)\f$
 */
class UClNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  UClNode();

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UClNode)
IS_R_NODE(UClNode)

inline UClNode::UClNode() {
  setName("uCl");
}

#endif

