/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UCNNODE_CUH
#define BIM_NPZD_UCNNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^{CN}\f$; 
 *
 * \f$u^{CN} \sim \mathcal{N}(0,1)\f$
 */
class UCNNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  UCNNode();

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UCNNode)
IS_R_NODE(UCNNode)

inline UCNNode::UCNNode() {
  setName("uCN");
}

#endif

