/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UCNODE_CUH
#define BIM_NPZD_UCNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^C\f$; 
 *
 * \f$u^C \sim \mathcal{N}(0,1)\f$
 */
class UCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  UCNode();

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UCNode)
IS_R_NODE(UCNode)

inline UCNode::UCNode() {
  setName("uC");
}

#endif

