/**
 * @file
 * 
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UENODE_CUH
#define BIM_NPZD_UENODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^E\f$; 
 *
 * \f$u^E \sim \mathcal{N}(0,1)\f$
 */
class UENode : public bi::BayesNode {
public:

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UENode)
IS_R_NODE(UENode)

#endif

