/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UNCNODE_CUH
#define BIM_NPZD_UNCNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^{NC}\f$; 
 *
 * \f$u^{NC} \sim \mathcal{N}(0,1)\f$
 */
class UNCNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  UNCNode();

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UNCNode)
IS_R_NODE(UNCNode)

inline UNCNode::UNCNode() {
  setName("uNC");
}

#endif

