/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_UQNODE_CUH
#define BIM_NPZD_UQNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^Q\f$; 
 *
 * \f$u^Q \sim \mathcal{N}(0,1)\f$
 */
class UQNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  UQNode();

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(UQNode)
IS_R_NODE(UQNode)

inline UQNode::UQNode() {
  setName("uQ");
}

#endif

