/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_URNODE_CUH
#define BIM_NPZD_URNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$u^R\f$; 
 *
 * \f$u^R \sim \mathcal{N}(0,1)\f$
 */
class URNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  URNode();

};

#include "bi/model/NodeRandomTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_GAUSSIAN(URNode)
IS_R_NODE(URNode)

inline URNode::URNode() {
  setName("uR");
}

#endif

