/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ZETAENODE_CUH
#define BIM_NPZD_ZETAENODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\zeta^E\f$; Zooplankton grazing efficiency
 *
 * \f$0.32\f$
 */
class ZetaENode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  ZetaENode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(ZetaENode)

inline ZetaENode::ZetaENode() {
  setName("zetaE");
}

#endif

