/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ZETAQNODE_CUH
#define BIM_NPZD_ZETAQNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\zeta^Q\f$; Z quadratic mortality term
 *
 * \f$0.02\f$
 */
class ZetaQNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  ZetaQNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(ZetaQNode)

inline ZetaQNode::ZetaQNode() {
  setName("zetaQ");
}

#endif

