/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ZETALNODE_CUH
#define BIM_NPZD_ZETALNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\zeta^L\f$; Z linear mortality term
 *
 * \f$0.01\f$
 */
class ZetaLNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  ZetaLNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(ZetaLNode)

inline ZetaLNode::ZetaLNode() {
  setName("zetaL");
}

#endif

