/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ZETAINODE_CUH
#define BIM_NPZD_ZETAINODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\zeta^I\f$; Max Z ingestion rate
 *
 * \f$1\f$
 */
class ZetaINode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  ZetaINode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(ZetaINode)

inline ZetaINode::ZetaINode() {
  setName("zetaI");
}

#endif

