/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_NPZD_ZETACLNODE_CUH
#define BIM_NPZD_ZETACLNODE_CUH

#include "bi/model/BayesNode.hpp"
#include "bi/cuda/cuda.hpp"

/**
 * \f$\zeta^{Cl}\f$; Zooplankton clearance rate
 *
 * \f$0.08\f$
 */
class ZetaClNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  ZetaClNode();

};

#include "bi/model/NodeStaticTraits.hpp"
#include "bi/model/NodeTypeTraits.hpp"

IS_IN_NODE(ZetaClNode)

inline ZetaClNode::ZetaClNode() {
  setName("zetaCl");
}

#endif

