function vars = papernames ()
    vars = {
        'K_W';
        'a_{Ch}';
        'S_D';
        'f_D';
        'PDF';
        'ZDF';
        '\mu_{g^{max}}';
        '\mu_{\lambda^{max}}';
        '\mu_{R_N}';
        '\mu_{a_N}';
        '\mu_{I_Z}';
        '\mu_{Cl_Z}';
        '\mu_{E_Z}';
        '\mu_{r_D}';
        '\mu_{m_Q}';
        'g^{max}';
        '\lambda^{max}';
        'R_N';
        'a_N';
        'I_Z';
        'Cl_Z';
        'E_Z';
        'r_D';
        'm_Q';
        'EZ';
        'Chla';
        'P';
        'Z';
        'D';
        'N';
    };
end
